spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db
    username: root
    password: 15082004

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/bookstore-realm/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}