spring:
  application:
    name: promotion-service

  datasource:
    url: jdbc:mysql://localhost:3306/promotion_service_db
    username: root
    password: 15082004

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: promotion-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8180/realms/bookstore/protocol/openid-connect/certs

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.security: DEBUG