spring:
  application:
    name: auth-service

keycloak:
  auth-server-url: http://localhost:8180
  realm: bookstore-realm
  resource: auth-service
  credentials:
    secret: 'UyOgcuXXvbYO11f3KzFcrwaRMh9gRo3F'
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8080