spring:
  application:
    name: auth-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: auth-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bookstore-realm

keycloak:
  auth-server-url: http://localhost:8180
  realm: bookstore-realm
  resource: auth-service
  credentials:
    secret: 'UyOgcuXXvbYO11f3KzFcrwaRMh9gRo3F'
    
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8080